### ISSUE TITLE
Potential matches are calculated and shown on the matches page.

### ISSUE THREAD

**Issue by abhasin3** [cse442-fall-2019-offering/442projects-spotme-inc#31]
The user should be able to see different matches when they go the the match page.  The matches should be in descending order (from greatest to least) based on their match score (which is calculated based on their distance).

Accepted Tests
*  The match list should display potential matches based on the match score
* The users listed should all be different people

**Comment by montanaq** [comment]
Listing the potential matches has been implemented.
